type Photo {
  id: String!
  file: String!
  caption: String
  user: User!
  userId: String!
  hashtags: [Hashtag!]!
  likes: Int!
  createdAt: String!
  updatedAt: String!
}

type Hashtag {
  id: String!
  hashtag: String!
  photos(page: Int!): [Photo!]!
  totalPhotos: Int!
  createdAt: String!
  updatedAt: String!
}

type Like {
  id: String!
  photo: Photo!
  photoId: String!
  user: User!
  userId: String!
  createdAt: String!
  updatedAt: String!
}
